pipeline {
agent any

environment {
    AWS_REGION = "ap-south-2"
    ECR_REGISTRY = "197103521525.dkr.ecr.ap-south-2.amazonaws.com"
    ECR_REPO = "${ECR_REGISTRY}/frontend"
    IMAGE_TAG = "${BUILD_NUMBER}"
    CLUSTER_NAME = "mern-app-deployment"
    NAMESPACE = "wanderlust"
}

stages {

    stage('Checkout') {
        steps {
            git branch: 'dev', url: 'https://github.com/ApurvGujjar07/MERN-app-deployment.git'
        }
    }

    stage('Login to ECR') {
        steps {
            withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'AWSCred']]) {
                sh '''
                aws ecr get-login-password --region $AWS_REGION | \
                docker login --username AWS --password-stdin $ECR_REGISTRY
                '''
            }
        }
    }

    stage('Build Image') {
        steps {
            dir('frontend') {
                sh 'docker build -t $ECR_REPO:$IMAGE_TAG .'
            }
        }
    }

    stage('Push Image') {
        steps {
            sh 'docker push $ECR_REPO:$IMAGE_TAG'
        }
    }

    stage('Deploy to EKS') {
        steps {
            withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'AWSCred']]) {
                sh '''
                aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

                kubectl get ns $NAMESPACE || kubectl create ns $NAMESPACE

                echo "Applying frontend manifests..."

                # ✅ FIXED FILE NAMES
                kubectl apply -f kubernetes/frontend-deploy.yaml -n $NAMESPACE
                kubectl apply -f kubernetes/frontend-svc.yml -n $NAMESPACE

                echo "Updating image..."

                kubectl set image deployment/frontend-deployment \
                frontend=$ECR_REPO:$IMAGE_TAG -n $NAMESPACE

                kubectl rollout status deployment/frontend-deployment -n $NAMESPACE
                '''
            }
        }
    }
}

}

