pipeline {
agent any

environment {
    AWS_REGION = "ap-south-2"
    ECR_REGISTRY = "197103521525.dkr.ecr.ap-south-2.amazonaws.com"
    ECR_REPO = "${ECR_REGISTRY}/backend"
    IMAGE_TAG = "${BUILD_NUMBER}"
    CLUSTER_NAME = "mern-app-deployment"
    NAMESPACE = "wanderlust"
}

stages {

    // ===================== CHECKOUT =====================
    stage('Checkout') {
        steps {
            git branch: 'dev', url: 'https://github.com/ApurvGujjar07/MERN-app-deployment.git'
        }
    }

    // ===================== LOGIN TO ECR =====================
    stage('Login to ECR') {
        steps {
            withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'AWSCred']]) {
                sh '''
                aws ecr get-login-password --region $AWS_REGION | \
                docker login --username AWS --password-stdin $ECR_REGISTRY
                '''
            }
        }
    }

    // ===================== BUILD IMAGE =====================
    stage('Build Image') {
        steps {
            dir('backend') {
                sh 'docker build -t $ECR_REPO:$IMAGE_TAG .'
            }
        }
    }

    // ===================== PUSH IMAGE =====================
    stage('Push Image') {
        steps {
            sh 'docker push $ECR_REPO:$IMAGE_TAG'
        }
    }

    // ===================== DEPLOY =====================
    stage('Deploy to EKS') {
        steps {
            withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'AWSCred']]) {
                sh '''
                # Configure kubectl
                aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

                # Ensure namespace exists
                kubectl get ns $NAMESPACE || kubectl create ns $NAMESPACE

                # Apply manifests
                kubectl apply -f k8s/backend-deployment.yaml -n $NAMESPACE
                kubectl apply -f k8s/backend-service.yaml -n $NAMESPACE

                # Update image
                kubectl set image deployment/backend-deployment \
                backend=$ECR_REPO:$IMAGE_TAG -n $NAMESPACE

                # Wait for rollout
                kubectl rollout status deployment/backend-deployment -n $NAMESPACE
                '''
            }
        }
    }
}

}

